# Generated by Django 2.0.6 on 2018-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'Normalverteilung'), ('2', 'Gleichverteilung'), ('3', 'Binomialverteilung ')], default='1', max_length=1)),
                ('source', models.CharField(choices=[('1', 'Datei'), ('2', 'Eingabe')], default='1', max_length=1)),
                ('file', models.FileField(upload_to='media/')),
                ('data1', models.TextField(default='')),
                ('data2', models.TextField(default='')),
            ],
        ),
    ]
